stages:
  - Prepare
  - Build
  - Test
  - Inspect
  - Deploy
  - Clean
  
Npm_install:
  stage: Build
  tags:
    - node
  script:
   - npm install --only=dev
   - npm install
  artifacts:
    paths:
      - node_modules/
    expire_in: 10 min

Mocha_tests:
  stage: Test
  tags:
    - node
  script:
   - npm test
  artifacts:
    paths:
      - coverage/
      - test-results.xml
    expire_in: 10 min
  allow_failure: true
    
sonarqube:
  stage: Inspect
  tags:
    - sonar
  script:
    - sonar-scanner

Deploy_to_test:
  stage: Deploy
  tags:
    - deploy
  script:
    - echo "Deploy to test server"
    - cp -f -r ../StageCoach-API/* /api/www-api-test/
  environment:
    name: Test
    url: https://145.97.16.184:8081
  only:
  - develop

Deploy_to_acceptance:
  stage: Deploy
  script:
    - echo "Deploy to acceptance server"
    - cp -f -r ../StageCoach-API/* /api/www-api-acceptance/
  environment:
    name: Acceptance
    url: https://145.97.16.184:8082
  only:
  - master
  when: manual

Deploy_to_production:
  stage: Deploy
  script:
    - echo "Deploy to acceptance server"
    - cp -f -r ../StageCoach-API/* /api/www-api-production/
  environment:
    name: Production
    url: https://145.97.16.184:8083
  only:
  - master
  when: manual
