stages:
  - Deploy
  - Clean
  
variables:
    TARGET_DIR: home/stagecoach/test/$CI_PROJECT_NAME


Deploy_to_test:
  stage: Deploy
  script:
    - echo "Deploy to test server"
    - ssh -p22 145.97.16.184 "rm -rf projects/stagecoach-api/test"
    - scp -P22 -r . stagecoach@145.97.16.184:rojects/stagecoach-api/test"
  environment:
    name: Test
    url: https://145.97.16.184:3002
  only:
  - develop

Deploy_to_acceptance:
  stage: Deploy
  script:
    - echo "Deploy to acceptance server"
  environment:
    name: Acceptance
    url: https://145.97.16.184:3001
  only:
  - master

Deploy_to_production:
  stage: Deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: Acceptance
    url: https://145.97.16.184:3000
  when: manual
  only:
  - master
