stages:
  - Prepare
  - Build
  - Test
  - Inspect
  - Clean

Prepare_Build_Job:
  stage: Prepare
  script:
   - npm install --only=dev
  artifacts:
    paths:
      - node_modules/
  expire_in: 5 min
   
Execute_Tests_Job:
  stage: Test
  script:
   - npm test
   - sonar-scanner
   
#Analysis_Job:
#  stage: Inspect
#  script:
#   - sonar-scanner