stages:
  - Prepare
  - Build
  - Test
  - Inspect
  - Deploy
  - Clean

Deploy_to_test:
  stage: Deploy
  tags:
    - deploy
  script:
    - echo "Deploy to test server"
    - pwd
    - ls -a
    - cp -f -r ../StageCoach-API/* /api/www-api-staging/
  environment:
    name: Test
    url: https://145.97.16.184:3002
  only:
  - develop

Deploy_to_acceptance:
  stage: Deploy
  script:
    - echo "Deploy to acceptance server"
  environment:
    name: Acceptance
    url: https://145.97.16.184:3001
  only:
  - master

Deploy_to_production:
  stage: Deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: Acceptance
    url: https://145.97.16.184:3000
  when: manual
  only:
  - master
