cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/
    - test-results.xml
    - coverage/

stages:
  - Prepare
  - Build
  - Test
  - Inspect
  - Clean

Prepare_Build_Job:
  stage: Prepare
  script:
   - npm install --only=dev
   
Execute_Tests_Job:
  stage: Test
  script:
   - npm test
   - sonar-scanner
   
#Analysis_Job:
#  stage: Inspect
#  script:
#   - sonar-scanner