stages:
  - Prepare
  - Build
  - Test
  - Inspect
  - Clean

Npm_install:
  stage: Build
  script:
   - npm install --only=dev
   - npm install
  artifacts:
    paths:
      - node_modules/
    expire_in: 10 min
   
Mocha_tests:
  stage: Test
  script:
   - npm test
  artifacts:
    paths:
      - coverage/
      - test-results.xml
    expire_in: 10 min
    
SonarQube_analysis:
  stage: Inspect
  script:
   - sonar-scanner