stages:
  - Prepare
  - Build
  - Test
  - Inspect
  - Clean

Build_Job:
  stage: Build
  script:
   - npm install --only=dev
   - npm install
  artifacts:
    paths:
      - node_modules/
    expire_in: 10 min
   
Test_Job:
  stage: Test
  script:
   - npm test
  artifacts:
    paths:
      - coverage/
      - test-results.xml
    expire_in: 10 min
    
Analysis_Job:
  stage: Inspect
  script:
   - sonar-scanner