cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/

stages:
  - Prepare
  - Build
  - Test
  - Inspect
  - Clean

Prepare_Build_Job:
  stage: Prepare
  script:
   - echo "Hello world"
   - npm install --only=dev
   - npm test
   
Test_Job:
  stage: Test
  script:

Analysis_Job:
  stage: Inspect
  script:
   - sonar-scanner